# Generated by Django 3.1.2 on 2020-10-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
    ]
