# Generated by Django 3.1.2 on 2020-10-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0002_auto_20201011_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['upload_date']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
    ]
