# Generated by Django 3.1.2 on 2020-10-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0003_auto_20201011_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
